import { jsPDF } from "jspdf";
import { CheckupRecord } from "./vault";

interface AnalysisResult {
    summary?: string;
    patterns: { name: string; prevalence: string }[];
    severity: { level: string; advice: string[] };
    confidence: { level: string; note: string };
    // v2.1 Professional Data
    urgency_summary?: string;
    key_findings?: string[];
    differential_diagnosis?: { condition: string; likelihood: string; rationale: string }[];
    suggested_focus?: string[];
    follow_up_questions?: string[];
}

export function generateMedicalReport(
    symptoms: string,
    result: AnalysisResult,
    id?: string,
    timestamp?: number
) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);
    let y = 20;

    // --- Header ---
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(50, 50, 50);
    doc.text("Pluto Clinical Chat Transcript", margin, y);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    const dateStr = timestamp ? new Date(timestamp).toLocaleDateString() : new Date().toLocaleDateString();
    doc.text(dateStr, pageWidth - margin, y, { align: "right" });

    y += 15;

    // --- Helper for Chat Bubbles ---
    const addChatBubble = (role: "User" | "Pluto", text: string, color: string) => {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(role === "User" ? 0 : 0, role === "User" ? 0 : 51, role === "User" ? 0 : 102); // Black for User, Dark Blue for Pluto
        doc.text(role, margin, y);
        y += 6;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);

        const splitText = doc.splitTextToSize(text, contentWidth - 10);
        doc.text(splitText, margin + 5, y);
        y += (splitText.length * 5) + 10;

        // Page break check
        if (y > 270) {
            doc.addPage();
            y = 20;
        }
    };

    // 1. User Input
    addChatBubble("User", symptoms, "#000000");

    // 2. Urgent Response (if applicable)
    // 2. Urgent Response (if applicable)
    const level = result.severity?.level || "INFO";
    const advice = result.severity?.advice || [];

    if (level.includes("EMERGENCY") || level.includes("URGENT")) {
        const severityText = `⚠️ STATUS: ${level}\n\n${result.urgency_summary || advice[0] || "Urgent attention required."}`;
        addChatBubble("Pluto", severityText, "#cc0000");
    }

    // 3. Main Assessment
    const summaryText = result.summary || "Here is my clinical assessment based on your symptoms.";
    addChatBubble("Pluto", summaryText, "#003366");

    // 4. Clinical Context (Differentials & Findings) - Conversational Format
    let contextText = "Based on these patterns, here is the clinical context:\n\n";

    if (result.key_findings && result.key_findings.length > 0) {
        contextText += "Key Findings:\n" + result.key_findings.map(f => `• ${f}`).join("\n") + "\n\n";
    }

    if (result.differential_diagnosis && result.differential_diagnosis.length > 0) {
        contextText += "Possibilities to Consider:\n";
        result.differential_diagnosis.slice(0, 4).forEach(d => {
            contextText += `• ${d.condition} (${d.likelihood}): ${d.rationale}\n`;
        });
    }

    addChatBubble("Pluto", contextText, "#003366");

    // 5. Suggested Next Steps
    if (result.suggested_focus && result.suggested_focus.length > 0) {
        const focusText = "I recommend focusing on:\n" + result.suggested_focus.map(f => `• ${f}`).join("\n");
        addChatBubble("Pluto", focusText, "#003366");
    }

    // Disclaimer Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    const disclaimer = "Generated by Pluto Health AI. Not a medical diagnosis. Verify all info.";
    doc.text(disclaimer, margin, pageHeight - 10);

    // Return the doc for saving by the caller
    return doc;
}
